#!/bin/sh

cpu_usage=$(mpstat 1 1 | awk '/秒/ {printf("%s\n", $(NF-0))}' | awk '{a=100-$1}END{print a}')

cpu_whole=`printf ${cpu_usage%.*}`

if [[ $cpuwhole -ge 1 ]]
then
    true
    #update var
elif [[ $cpuwhole -ge 1 ]]
then
    true
    #update var
else
    true
    #update var
fi;

echo $cpu_usage


